print("Welcome to the tip calculator!")
amount = float(input("What was the total bill? $"))
tip_percent = int(input("How much tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill? "))
payment = (amount / people) * ((100 + tip_percent)/100)
print(f"{payment:.2f}")